### PR TITLE
Migrated to ChibiOS 21 6

### PR DESCRIPTION
**Pull request by abusous2000**
Migrated to ChibiOS 21 6

### CODE REVIEW

**Comment by abusous2000** [comment]
Migrate to ChibiOS 21.6

**Comment by abusous2000** [comment]
commit

**Comment by abusous2000** [comment]
Migrated to ChibiOS 21 6

**Review by abusous2000 — COMMENTED** [review]
approve

**Review by abusous2000pr — APPROVED** [review]

**Comment by abusous2000pr** [comment]
fine

**Review by abusous2000pr — APPROVED** [review]

**Review by abusous2000 — COMMENTED** [review]
good

**Comment by abusous2000** [comment]
merge

**Review by abusous2000pr — APPROVED** [review]
I approve

**Comment by abusous2000pr** [comment]
I approve

**Pull request closed without merging**
